"""
Publish Pact Contract to PactFlow (Cloud Pact Broker)
======================================================
This script uploads the consumer contract JSON to the cloud Pact Broker
(PactFlow at https://deepintent.pactflow.io).

WHY publish to a cloud broker?
  In a team setup, the contract must not be a local file. If it is:
    - a Provider team cannot access it
    - CI/CD cannot access it
    - No visibility into which consumers depend on which providers

  With PactFlow (cloud broker):
    - Consumer publishes once → contract is stored centrally
    - Any provider anywhere can fetch and verify it
    - PactFlow UI shows which consumer-provider pairs are compatible
    - Can be tagged by version/branch/environment

HOW TO RUN:
  1. Set your PactFlow API token as an environment variable:
       Windows PowerShell:
         $env:PACT_BROKER_TOKEN = "your-read-write-token-here"
       Mac/Linux:
         export PACT_BROKER_TOKEN=your-read-write-token-here

  2. Run this script from the project root:
       python scripts/publish_pact.py

  3. Open https://deepintent.pactflow.io to see the published contract

HOW TO GET THE TOKEN:
  1. Go to https://deepintent.pactflow.io
  2. Settings → API Tokens → copy the "Read/write token"

CONSUMER VERSION:
  In production, this is typically the git commit hash or build number.
  Here we use a simple version string, overridable via CONSUMER_VERSION env var.
  Example: $env:CONSUMER_VERSION = "abc1234" (use git commit hash in CI)
"""

import json
import os
import sys
import requests

# ── Configuration ─────────────────────────────────────────────────────────────

# PactFlow cloud broker URL — not a secret, safe to hardcode
PACT_BROKER_URL = "https://deepintent.pactflow.io"

# API token — MUST come from environment variable, never hardcode secrets
PACT_BROKER_TOKEN = os.environ.get("PACT_BROKER_TOKEN")

# Consumer version tag — in CI use git commit hash; for local dev use "1.0.0"
# Override: $env:CONSUMER_VERSION = "abc1234"
CONSUMER_VERSION = os.environ.get("CONSUMER_VERSION", "1.0.1")

# Branch name — tells PactFlow which branch this contract came from.
# In CI use: os.environ.get("GIT_BRANCH") or parse from git.
# Locally defaults to "main" so the compatibility matrix shows green.
CONSUMER_BRANCH = os.environ.get("CONSUMER_BRANCH", "main")

# Path to the pact JSON generated by consumer tests
PACT_FILE = "pacts/BooksCatalogue-CoursesCatalogue-pact.json"


# ── Validation ────────────────────────────────────────────────────────────────

if not PACT_BROKER_TOKEN:
    print(
        "\n[ERROR] PACT_BROKER_TOKEN environment variable is not set.\n"
        "Set it before running this script:\n\n"
        "  Windows PowerShell:\n"
        "    $env:PACT_BROKER_TOKEN = 'your-read-write-token-here'\n\n"
        "  Mac/Linux:\n"
        "    export PACT_BROKER_TOKEN=your-read-write-token-here\n\n"
        "Get the token from: https://deepintent.pactflow.io → Settings → API Tokens\n"
    )
    sys.exit(1)

if not os.path.exists(PACT_FILE):
    print(
        f"\n[ERROR] Pact file not found: {PACT_FILE}\n"
        "Run consumer tests first to generate it:\n"
        "  pytest tests/consumer/ -v\n"
    )
    sys.exit(1)


# ── Load pact JSON ────────────────────────────────────────────────────────────

with open(PACT_FILE) as f:
    pact = json.load(f)

consumer = pact["consumer"]["name"]   # "BooksCatalogue"
provider = pact["provider"]["name"]   # "CoursesCatalogue"


# ── Publish to PactFlow ───────────────────────────────────────────────────────
# Pact Broker REST API for publishing a contract:
#   PUT /pacts/provider/{provider}/consumer/{consumer}/version/{version}
#   Authorization: Bearer <token>
#   Content-Type: application/json
#   Body: the full pact JSON

url = f"{PACT_BROKER_URL}/pacts/provider/{provider}/consumer/{consumer}/version/{CONSUMER_VERSION}"

headers = {
    "Authorization": f"Bearer {PACT_BROKER_TOKEN}",
    "Content-Type": "application/json",
}

print(f"\nPublishing contract to PactFlow...")
print(f"  Consumer : {consumer}")
print(f"  Provider : {provider}")
print(f"  Version  : {CONSUMER_VERSION}")
print(f"  Branch   : {CONSUMER_BRANCH}")
print(f"  Broker   : {PACT_BROKER_URL}")
print(f"  URL      : {url}\n")

response = requests.put(url, json=pact, headers=headers)

if response.status_code not in (200, 201):
    print(f"[FAILED] HTTP {response.status_code}")
    print(f"  Response: {response.text}\n")
    sys.exit(1)

print(f"[SUCCESS] Contract published successfully!")

# ── Set branch on version (modern PactFlow "branches" API) ───────────────────
# This is what powers the "main branch version" badge on the Applications dashboard.
branch_url = f"{PACT_BROKER_URL}/pacticipants/{consumer}/versions/{CONSUMER_VERSION}"
branch_response = requests.patch(
    branch_url,
    json={"branch": CONSUMER_BRANCH},
    headers={**headers, "Content-Type": "application/merge-patch+json"},
)
if branch_response.status_code in (200, 201):
    print(f"[SUCCESS] Version branch set to '{CONSUMER_BRANCH}'")
else:
    print(f"[WARN] Branch set failed: HTTP {branch_response.status_code} — {branch_response.text}")

# ── Set mainBranch on both pacticipants (idempotent, safe to run every time) ─
# Tells PactFlow which branch is "main" so Applications dashboard shows the badge.
for participant in [consumer, provider]:
    mb_url = f"{PACT_BROKER_URL}/pacticipants/{participant}"
    mb_res = requests.patch(
        mb_url,
        json={"mainBranch": CONSUMER_BRANCH},
        headers={**headers, "Content-Type": "application/merge-patch+json"},
    )
    if mb_res.status_code in (200, 201):
        print(f"[SUCCESS] mainBranch set to '{CONSUMER_BRANCH}' for {participant}")
    else:
        print(f"[WARN] mainBranch set failed for {participant}: HTTP {mb_res.status_code}")

print(f"  View at: {PACT_BROKER_URL}/pacts/provider/{provider}/consumer/{consumer}/latest\n")
